Models/Alunos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AppDB.Models;

public class Alunos
{
    public int Id { get; set; }

    [MaxLength(20)]
    [Description("Nome do aluno")]
    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    public string Nome { get; set; }

    [Description("Turma do aluno")]
    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    public string Turma { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    public decimal Nota1 { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    public decimal Nota2 { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    public decimal Nota3 { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    public int Faltas { get; set; }

    [NotMapped]
    public decimal Media { get; set; }
}

Models/ErrorViewModel.cs
namespace AppDB.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/AlunosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AppDB.Models;

namespace AppDB.Controllers;

public class AlunosController : Controller
{
    private readonly ILogger<AlunosController> _logger;

    private readonly AlunosDbContext _context;

    public AlunosController(ILogger<AlunosController> logger, AlunosDbContext context)
    {
        _logger = logger;
        _context = context;
    }

    public IActionResult Index()
    {
        var alunos = _context.alunos.ToList();

        foreach (var aluno in alunos)
        {
            aluno.Media = (aluno.Nota1 + aluno.Nota2 + aluno.Nota3) / 3;
        }

        return View(alunos);
    }

    public IActionResult InserirAluno()
    {
        return View();
    }

    [HttpPost]
    public IActionResult InserirAluno(Alunos aluno)
    {
        if (ModelState.IsValid)
        {
            _context.alunos.Add(aluno);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        return View(aluno);
    }

    public IActionResult AlterarAluno(int id)
    {
        var alunos = _context.alunos.Find(id);

        if (alunos == null)
        {
            return RedirectToAction(nameof(Index));
        }

        return View(alunos);
    }

    [HttpPost]
    public IActionResult AlterarAluno(Alunos aluno)
    {
        var alunoBanco = _context.alunos.Find(aluno.Id);
        alunoBanco.Nome = aluno.Nome;
        alunoBanco.Turma = aluno.Turma;
        alunoBanco.Nota1 = aluno.Nota1;
        alunoBanco.Nota2 = aluno.Nota2;
        alunoBanco.Nota3 = aluno.Nota3;
        alunoBanco.Faltas = aluno.Faltas;

        _context.alunos.Update(alunoBanco);
        _context.SaveChanges();

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Detalhes(int id)
    {
        var aluno = _context.alunos.Find(id);

        if (aluno == null)
        {
            return RedirectToAction(nameof(Index));
        }

        aluno.Media = (aluno.Nota1 + aluno.Nota2 + aluno.Nota3) / 3;

        return View(aluno);
    }

    public IActionResult ExcluirAluno(int id)
    {
        var aluno = _context.alunos.Find(id);

        if (aluno == null)
        {
            return RedirectToAction(nameof(Index));
        }

        aluno.Media = (aluno.Nota1 + aluno.Nota2 + aluno.Nota3) / 3;

        return View(aluno);
    }

    [HttpPost]
    public IActionResult ExcluirAluno(Alunos aluno)
    {
        var alunoBanco = _context.alunos.Find(aluno.Id);

        _context.alunos.Remove(alunoBanco);
        _context.SaveChanges();

        return RedirectToAction(nameof(Index));
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AppDB.Models;

namespace AppDB.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Alunos/AlterarAluno.cshtml
@model AppDB.Models.Alunos
@{
    ViewData["Title"] = "Alterar aluno";

    <h1>Alterar Dados do Aluno</h1>

    <hr />

    <div class="row">
        <div class="row-md-4">
            <form asp-action="AlterarAluno">
                <div class="form-group">
                    <label asp-for="Nome" class="control-label">Nome do Aluno: </label>
                    <input asp-for="Nome" class="form-control"></input>
                </div>
                <div class="form-group">
                    <label asp-for="Turma" class="control-label">Turma do Aluno: </label>
                    <input asp-for="Turma" class="form-control"></input>
                </div>
                <div class="form-group">
                    <label asp-for="Nota1" class="form-label">Primeira Nota: </label>
                    <input asp-for="Nota1" class="form-control"></input>
                </div>
                <div class="form-group">
                    <label asp-for="Nota2" class="form-label">Segunda Nota: </label>
                    <input asp-for="Nota2" class="form-control"></input>
                </div>
                <div class="form-group">
                    <label asp-for="Nota3" class="form-label">Terceira Nota: </label>
                    <input asp-for="Nota3" class="form-control"></input>
                </div>
                <div class="form-group">
                    <label asp-for="Faltas" class="form-label">Quantidade de Faltas: </label>
                    <input asp-for="Faltas" class="form-control"></input>
                </div>
                <div class="form-group">
                    <input type="submit" value="Alterar" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
    <hr />
    <div>
        <a asp-action="Index">Voltar</a>
    </div>
}

Views/Alunos/Detalhes.cshtml
@model AppDB.Models.Alunos

@{
    ViewData["title"] = "Detalhes do aluno";
}

<h1>Detalhes</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nome)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nome)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Turma)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Turma)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nota1)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nota1)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nota2)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nota2)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nota3)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nota3)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Faltas)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Faltas)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Media)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Media)
        </dt>
    </dl>
</div>
<a asp-action="AlterarAluno" asp-route-id="@Model.Id">Alterar</a> |
<a asp-action="Index">Voltar</a>

Views/Alunos/ExcluirAluno.cshtml
@model AppDB.Models.Alunos

@{
    ViewData["title"] = "Excluir aluno";
}

<h1 style="color: red;">Deseja realmente deletar esse aluno? Essa operação é irreversível</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nome)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nome)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Turma)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Turma)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nota1)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nota1)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nota2)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nota2)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nota3)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nota3)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Faltas)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Faltas)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Media)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Media)
        </dt>
    </dl>
</div>
<form asp-action="ExcluirAluno">
    <input type="submit" value="Excluir" class="btn btn-danger" />
</form>

<br>
<a asp-action="Index">Voltar</a>

Views/Alunos/Index.cshtml
@model IEnumerable<AppDB.Models.Alunos>

@{
    ViewData["Title"] = "Listagem de Alunos";
}

<h2>Alunos</h2>

<p>
    <a asp-action="InserirAluno">Novo Aluno</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turma)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Faltas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Media)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Turma)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Nota1)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Nota2)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Nota3)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Faltas)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Media)
                </td>
                <td>
                    <a asp-action="AlterarAluno" asp-route-id="@item.Id">Alterar</a> |
                    <a asp-action="Detalhes" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="ExcluirAluno" asp-route-id="@item.Id">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Alunos/InserirAluno.cshtml
@model AppDB.Models.Alunos
@{
    ViewData["Title"] = "Inserir Novo Aluno";

    <h1>Inserir novo aluno</h1>

    <div class="row">
        <div class="row-md-4">
            <form asp-action="InserirAluno">
                <div class="form-group">
                    <label asp-for="Nome" class="control-label">Nome do Aluno: </label>
                    <input asp-for="Nome" class="form-control"></input>
                </div>
                <div class="form-group">
                    <label asp-for="Turma" class="control-label">Turma do Aluno: </label>
                    <input asp-for="Turma" class="form-control"></input>
                </div>
                <div class="form-group">
                    <label asp-for="Nota1" class="form-label">Primeira Nota: </label>
                    <input asp-for="Nota1" class="form-control"></input>
                </div>
                <div class="form-group">
                    <label asp-for="Nota2" class="form-label">Segunda Nota: </label>
                    <input asp-for="Nota2" class="form-control"></input>
                </div>
                <div class="form-group">
                    <label asp-for="Nota3" class="form-label">Terceira Nota: </label>
                    <input asp-for="Nota3" class="form-control"></input>
                </div>
                <div class="form-group">
                    <label asp-for="Faltas" class="form-label">Quantidade de Faltas: </label>
                    <input asp-for="Faltas" class="form-control"></input>
                </div>
                <div class="form-group">
                    <input type="submit" value="Inserir" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
    <hr />
    <div>
        <a asp-action="Index">Voltar</a>
    </div>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppDB.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppDB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alunos"
                                asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AppDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>